### ISSUE TITLE
Only "IN" in INNER JOIN Highlighted

### ISSUE THREAD

**Issue by sshaw** [alekseyl/niceql#1]
<img width="1077" alt="query" src="https://user-images.githubusercontent.com/17570/40627860-63c314e8-628f-11e8-8d4c-ce29418c176a.png">

Also, is there a way to output the formatted SQL to the log as part of normal query? Wasn't clear from docs if this is possible.

**Comment by alekseyl** [comment]
You want only log it prettified, not execute? Am I right? 

Right now there isn't any config options for pretty logging, except for config.pg_adapter_with_nicesql = true and this will run all things prettified and logging also will go prettified.

I would not recommend to run prettified SQL in production cause it makes queries longer and potentially brings one more place to raise an error. 

But only to log prettified is a good idea, so look for prettify_active_record_log_output config option in a 0.1.15+ gem versions. 


JOIN refactored also in 0.1.15+ versions

**Comment by barrywoolgar** [comment]
I think this is still broken in 0.1.16, I think you need to change the `INLINE_VERBS` regex part to use `IN[^N]` instead of just `IN`. Can do a PR if you'd like!

![screen shot 2018-05-29 at 10 20 25](https://user-images.githubusercontent.com/6248009/40649983-21a792f0-632a-11e8-903e-76b3a78c5d2e.png)

Thanks for this gem

**Comment by alekseyl** [comment]
yeeah..  NEW_LINE_VERBS must go first. will do this ASAP with test.

**Comment by alekseyl** [comment]
DONE + test for prettify_sql

**Comment by alekseyl** [comment]
try 0.1.18 version with prettify_active_record_log_output = true
