### ISSUE TITLE
Allows Install On Older Ruby, But Actually Requires Ruby >=2.3

### ISSUE THREAD

**Issue by maurice-does-software** [alekseyl/niceql#11]
Some of us are stuck using older Ruby versions (in my case, 2.2.4p230) for legacy apps. I was excited to download and try this gem, but when starting up the rails console, it immediately failed with this error:

> /home/maurice/.rvm/gems/ruby-2.2.4@my_project_name/gems/bundler-1.13.6/lib/bundler/runtime.rb:91:in `require': /home/maurice/.rvm/gems/ruby-2.2.4@insureio/gems/niceql-0.1.23/lib/niceql.rb:85: syntax error, unexpected '.' (SyntaxError)
> ...ine..-1] : original_sql_query&.lines

That looks to be failing due to the lack of the safe navigation operator introduced in Ruby 2.3. It would be greatly appreciated if you could either more clearly document the dependencies, or make the gem backward-compatible with older rubies.

**Comment by alekseyl** [comment]
dependency upgraded to ruby >= 2.3

The problem is not only with the &. operator, but also with the <<~

https://infinum.co/the-capsized-eight/multiline-strings-ruby-2-3-0-the-squiggly-heredoc

I can replace the one usage of &. to `obj && obj.call `, but I can't do that for <<~, the alternative would be unacceptably ugly, sorry :(.
